#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=16,vmem=31gb,walltime=10:00:00

## modules
#echo "Loading modules"
#module unload python
#module load dipy/dev
#module load nodejs
#echo "Finished loading modules"

#export PYTHONPATH=/N/u/brlife/git/nibabel:$PYTHONPATH

#echo "setting miniconda path..."
#unset PYTHONPATH
#export PATH=/N/u/gberto/Karst/miniconda2/bin:$PATH 

set -e
set -x

#execute app
echo "Bundle segmentation with multi-LAP just started..."
#./run.sh
SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/dipy:0.16.0 ./run.sh

ret=$?
if [ ! $ret -eq 0 ]; then
	exit $ret
fi

#removing files
rm *.nii.gz -f
rm *.tck
rm -r tractograms_directory -f
rm -r examples_directory* -f
rm kdt -f
rm prototypes.npy -f
rm distance* -f

echo "Complete"
